services:
  gr00t-dev-jahn:
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: ${DOCKERFILE_PATH}
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        DEV_USER: ${DEV_USER}
        DEV_UID: ${DEV_UID}
        DEV_GID: ${DEV_GID}
        DEV_HOME: ${DOCKER_HOME}
        WORKDIR: ${WORKDIR}
        ZK_VERSION: ${ZK_VERSION}

    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    working_dir: ${WORKDIR}

    stdin_open: true
    tty: true
    gpus: all
    command: sleep infinity

    environment:
      HOME: ${DOCKER_HOME}
      USER: ${DEV_USER}
      WORKDIR: ${WORKDIR}
      XDG_CONFIG_HOME: ${DOCKER_HOME}/.config
      XDG_DATA_HOME: ${DOCKER_HOME}/.local/share
      XDG_STATE_HOME: ${DOCKER_HOME}/.local/state
      XDG_CACHE_HOME: ${DOCKER_HOME}/.cache
      CARGO_HOME: ${DOCKER_HOME}/.cargo
      ZK_NOTEBOOK_DIR: ${DOCKER_HOME}/notebook
      TERM: xterm-256color
      DISPLAY: ${DISPLAY}
      XAUTHORITY: /tmp/Xauthority
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all

    volumes:
      - type: bind
        source: ${HOST_PROJECT_DIRECTORY}
        target: ${WORKDIR}

      - type: bind
        source: ${HOST_NVIM_CONFIG_DIRECTORY}
        target: ${DOCKER_HOME}/.config/nvim

      - type: bind
        source: ${HOST_NVIM_DATA_DIRECTORY}
        target: ${DOCKER_HOME}/.local/share/nvim

      - type: bind
        source: ${HOST_NOTEBOOK_DIRECTORY}
        target: ${DOCKER_HOME}/notebook

      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        read_only: true

      - type: bind
        source: ${HOME}/.Xauthority
        target: /tmp/Xauthority
        read_only: true

      - type: bind
        source: ${HOME}/.terminfo/x/xterm-kitty
        target: /home/${DEV_USER}/.terminfo/x/xterm-kitty
        read_only: true

      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
