services:
  foo-dev:
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: ${DOCKERFILE_PATH}
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        DEV_USER: ${DEV_USER}
        DEV_UID: ${DEV_UID}
        DEV_GID: ${DEV_GID}
        DEV_HOME: ${DOCKER_HOME}
        WORKDIR: ${WORKDIR}
        ZK_VERSION: ${ZK_VERSION}

    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    working_dir: ${WORKDIR}

    stdin_open: true
    tty: true

    environment:
      HOME: ${DOCKER_HOME}
      USER: ${DEV_USER}
      WORKDIR: ${WORKDIR}
      XDG_CONFIG_HOME: ${DOCKER_HOME}/.config
      XDG_DATA_HOME: ${DOCKER_HOME}/.local/share
      XDG_STATE_HOME: ${DOCKER_HOME}/.local/state
      XDG_CACHE_HOME: ${DOCKER_HOME}/.cache
      CARGO_HOME: ${DOCKER_HOME}/.cargo

    volumes:
      - ${HOST_PROJECT_DIRECTORY}:${WORKDIR}
      - ${HOST_NVIM_CONFIG_DIRECTORY}:${DOCKER_HOME}/.config/nvim
      - ${HOST_NVIM_DATA_DIRECTORY}:${DOCKER_HOME}/.local/share/nvim
      - ${HOST_NOTEBOOK_DIRECTORY}:${DOCKER_HOME}/notebook

    command: sleep infinity
